
resources:
  - repo: self
    clean: true
    fetchDepth: 1

trigger:
- PBI-44356
# Build and pub Nuget package for DocStore
# TODO make MyVersion just $(GitVersion.MajorMinorPatch) for master branch - perhaps - or GitVersion.NuGetVersionV2 NOT SURE
# So - when on develop the MyVersion ==  looks just fine.  
# When on a non-develop and non-master branch use

variables:
  GitVersion.SemVer: ''
  MyVersion: '$(GitVersion.MajorMinorPatch)-$(GitVersion.EscapedBranchName)-$(GitVersion.BuildMetaData)'

pool:
  vmImage: 'ubuntu-latest'

name: _WAKA_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)

steps:
- task: UseGitVersion@5
  displayName: gitversion
  inputs:
    versionSpec: '5.x'
    updateAssemblyInfo: false
    #https://github.com/GitTools/GitVersion/issues/2225

- task: NuGetToolInstaller@1

# - task: DotNetCoreCLI@2  
#   displayName: 'Create Forms NuGet package'
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/Microcharts.Forms.csproj'
#     #versioningScheme: byEnvVar
#     #versionEnvVar: 'GitVersion.SemVer'
#     packDirectory: '$(Build.ArtifactStagingDirectory)'
#     #nobuild: true
#     #includesource: true
#     #versionEnvVar: MyVersion
#     buildProperties: 'SymbolPackageFormat=snupkg'

- task: DotNetCoreCLI@2  
  displayName: 'Create Forms NuGet package'
  inputs:
    command: 'build'
    packagesToPack: '**/Microcharts.Droid.csproj'
    #versioningScheme: byEnvVar
    #versionEnvVar: 'GitVersion.SemVer'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    #nobuild: true
    #includesource: true
    #versionEnvVar: MyVersion
    #buildProperties: 'SymbolPackageFormat=snupkg'

- task: NuGetCommand@2 
  displayName: 'Create Core NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '**/Microcharts.Droid.csproj'
    #versioningScheme: byEnvVar
    #versionEnvVar: MyVersion
    #versionEnvVar: 'GitVersion.SemVer'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    #nobuild: true
    #includesource: true
    #buildProperties: 'SymbolPackageFormat=snupkg'


- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'


- task: NuGetCommand@2
  displayName: "Push to Nuget feed"
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '07581f72-b7dd-40bc-8318-ae6650290111'

